# Set default shell to fish
hostname *
login_shell /usr/bin/fish

hostname 192.168.1.*

# Setup fish to read its config from my-conf/fish
env XDG_CONFIG_HOME=$HOME/my-conf
copy --dest my-conf/fish/config.fish .config/fish/config.fish
