# Video quality
vo=gpu-next
profile=high-quality
hwdec=nvdec
deband=yes
tone-mapping=bt.2446a
glsl-shader="/home/nessie/.config/mpv/shaders/fsr.glsl"

# Playlist / playback
autocreate-playlist=filter

# Screenshots
screenshot-format=jxl
screenshot-jxl-distance=0
screenshot-jxl-effort=4
